name: Production & Staging Deploy

on:
  push:
    branches:
      - main
      # - preview

jobs:
  publish:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: npm install
        working-directory: ./

      - name: Build
        run: npm run build
        working-directory: ./

      # - name: Set environment
      #   id: set-env
      #   run: |
      #     echo "ENV_NAME=${{ github.ref_name == 'main' && '--env production' || '--env preview' }}" >> $GITHUB_ENV

      - name: Deploy
        id: cloudflare-wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: deploy --env production
          secrets: |
            NUXT_CF_ID
            NUXT_CF_SECRET
          # ENVIRONMENT: ${{ env.ENV_NAME }}
          ENVIRONMENT: production
        env:
          NUXT_CF_ID: ${{ secrets.NUXT_CF_ID }}
          NUXT_CF_SECRET: ${{ secrets.NUXT_CF_SECRET }}